/*
 * Auswahllisten für die Personalstammdaten: Krankenkassen (gesetzliche Kassen in Deutschland, Stand 2026 – Namen ändern
 * sich durch Fusionen; fehlt eine, „Sonstige“ wählen und im Info-Feld ergänzen) und Sprachen.
 */
export const HEALTH_INSURERS = [
  'AOK Baden-Württemberg',
  'AOK Bayern',
  'AOK Bremen/Bremerhaven',
  'AOK Hessen',
  'AOK Niedersachsen',
  'AOK Nordost',
  'AOK NordWest',
  'AOK PLUS',
  'AOK Rheinland/Hamburg',
  'AOK Rheinland-Pfalz/Saarland',
  'AOK Sachsen-Anhalt',
  'BARMER',
  'DAK-Gesundheit',
  'Techniker Krankenkasse (TK)',
  'KKH Kaufmännische Krankenkasse',
  'hkk Krankenkasse',
  'HEK – Hanseatische Krankenkasse',
  'IKK classic',
  'IKK gesund plus',
  'IKK – Die Innovationskasse',
  'IKK Südwest',
  'BIG direkt gesund',
  'KNAPPSCHAFT',
  'SVLFG (Landwirtschaftliche Krankenkasse)',
  'Audi BKK',
  'BAHN-BKK',
  'BKK Akzo Nobel Bayern',
  'BKK Diakonie',
  'BKK DürkoppAdler',
  'BKK EUREGIO',
  'BKK exklusiv',
  'BKK Faber-Castell & Partner',
  'BKK firmus',
  'BKK Freudenberg',
  'BKK GILDEMEISTER SEIDENSTICKER',
  'BKK HENSCHEL Plus',
  'BKK Herkules',
  'BKK Linde',
  'BKK MAHLE',
  'bkk melitta hmr',
  'BKK Mobil',
  'BKK MTU',
  'BKK PFAFF',
  'BKK Pfalz',
  'BKK ProVita',
  'BKK Public',
  'BKK Rieker.RICOSTA.Weisser',
  'BKK Salzgitter',
  'BKK Scheufelen',
  'BKK SBH',
  'BKK Technoform',
  'BKK Textilgruppe Hof',
  'BKK VDN',
  'BKK VerbundPlus',
  'BKK Werra-Meissner',
  'BKK WIRTSCHAFT & FINANZEN',
  'BKK ZF & Partner',
  'BKK24',
  'Bertelsmann BKK',
  'BMW BKK',
  'Bosch BKK',
  'Continentale Betriebskrankenkasse',
  'Debeka BKK',
  'energie-BKK',
  'Heimat Krankenkasse',
  'Karl Mayer BKK',
  'Koenig & Bauer BKK',
  'Krones BKK',
  'Mercedes-Benz BKK',
  'Merck BKK',
  'mhplus Krankenkasse',
  'Novitas BKK',
  'pronova BKK',
  'R+V Betriebskrankenkasse',
  'Salus BKK',
  'SECURVITA Krankenkasse',
  'Siemens-Betriebskrankenkasse (SBK)',
  'SKD BKK',
  'Südzucker BKK',
  'TUI BKK',
  'VIACTIV Krankenkasse',
  'vivida bkk',
  'WMF BKK',
  'Privat versichert (PKV)',
  'Sonstige',
];

/** Sprachen der Mitarbeitenden; die ersten sieben gibt es auch als Sprache der Handy-App. */
export const LANGUAGES: { name: string; app?: string }[] = [
  { name: 'Deutsch', app: 'de' },
  { name: 'Englisch', app: 'en' },
  { name: 'Rumänisch', app: 'ro' },
  { name: 'Türkisch', app: 'tr' },
  { name: 'Polnisch', app: 'pl' },
  { name: 'Kroatisch/Bosnisch/Serbisch', app: 'hr' },
  { name: 'Bulgarisch', app: 'bg' },
  { name: 'Arabisch' },
  { name: 'Ukrainisch' },
  { name: 'Russisch' },
  { name: 'Albanisch' },
  { name: 'Griechisch' },
  { name: 'Italienisch' },
  { name: 'Spanisch' },
  { name: 'Portugiesisch' },
  { name: 'Ungarisch' },
  { name: 'Slowakisch' },
  { name: 'Tschechisch' },
  { name: 'Persisch (Farsi/Dari)' },
  { name: 'Kurdisch' },
  { name: 'Tigrinya' },
  { name: 'Somali' },
  { name: 'Vietnamesisch' },
];

/** App-Sprache aus den gewählten Sprachen: erste, die die Handy-App kann (sonst Deutsch). */
export function appLanguageOf(languages: string[]): string {
  for (const l of languages) {
    const hit = LANGUAGES.find(
      (x) => x.name.toLowerCase() === l.trim().toLowerCase() || x.app === l.trim().toLowerCase(),
    );
    if (hit?.app) return hit.app;
  }
  return 'de';
}

/**
 * Staaten für „Staatsangehörigkeit“ (deutsche Kurzform). `free` = EU/EWR/Schweiz: Freizügigkeit, kein Aufenthaltstitel
 * zum Arbeiten nötig. Alle anderen brauchen einen Aufenthaltstitel, der die Beschäftigung erlaubt (§ 4a AufenthG).
 */
export const FREE_MOVEMENT_COUNTRIES = [
  'Deutschland',
  'Belgien',
  'Bulgarien',
  'Dänemark',
  'Estland',
  'Finnland',
  'Frankreich',
  'Griechenland',
  'Irland',
  'Island',
  'Italien',
  'Kroatien',
  'Lettland',
  'Liechtenstein',
  'Litauen',
  'Luxemburg',
  'Malta',
  'Niederlande',
  'Norwegen',
  'Österreich',
  'Polen',
  'Portugal',
  'Rumänien',
  'Schweden',
  'Schweiz',
  'Slowakei',
  'Slowenien',
  'Spanien',
  'Tschechien',
  'Ungarn',
  'Zypern',
] as const;

export const OTHER_COUNTRIES = [
  'Afghanistan',
  'Ägypten',
  'Albanien',
  'Algerien',
  'Andorra',
  'Angola',
  'Antigua und Barbuda',
  'Äquatorialguinea',
  'Argentinien',
  'Armenien',
  'Aserbaidschan',
  'Äthiopien',
  'Australien',
  'Bahamas',
  'Bahrain',
  'Bangladesch',
  'Barbados',
  'Belarus',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivien',
  'Bosnien und Herzegowina',
  'Botsuana',
  'Brasilien',
  'Brunei',
  'Burkina Faso',
  'Burundi',
  'Chile',
  'China',
  'Costa Rica',
  'Côte d’Ivoire',
  'Dominica',
  'Dominikanische Republik',
  'Dschibuti',
  'Ecuador',
  'El Salvador',
  'Eritrea',
  'Eswatini',
  'Fidschi',
  'Gabun',
  'Gambia',
  'Georgien',
  'Ghana',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Indien',
  'Indonesien',
  'Irak',
  'Iran',
  'Israel',
  'Jamaika',
  'Japan',
  'Jemen',
  'Jordanien',
  'Kambodscha',
  'Kamerun',
  'Kanada',
  'Kap Verde',
  'Kasachstan',
  'Katar',
  'Kenia',
  'Kirgisistan',
  'Kiribati',
  'Kolumbien',
  'Komoren',
  'Kongo',
  'Kongo, Demokratische Republik',
  'Korea, Republik (Südkorea)',
  'Korea, Demokratische Volksrepublik (Nordkorea)',
  'Kosovo',
  'Kuba',
  'Kuwait',
  'Laos',
  'Lesotho',
  'Libanon',
  'Liberia',
  'Libyen',
  'Madagaskar',
  'Malawi',
  'Malaysia',
  'Malediven',
  'Mali',
  'Marokko',
  'Marshallinseln',
  'Mauretanien',
  'Mauritius',
  'Mexiko',
  'Mikronesien',
  'Moldau',
  'Monaco',
  'Mongolei',
  'Montenegro',
  'Mosambik',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Neuseeland',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Nordmazedonien',
  'Oman',
  'Pakistan',
  'Palästinensische Gebiete',
  'Palau',
  'Panama',
  'Papua-Neuguinea',
  'Paraguay',
  'Peru',
  'Philippinen',
  'Ruanda',
  'Russland',
  'Salomonen',
  'Sambia',
  'Samoa',
  'San Marino',
  'São Tomé und Príncipe',
  'Saudi-Arabien',
  'Senegal',
  'Serbien',
  'Seychellen',
  'Sierra Leone',
  'Simbabwe',
  'Singapur',
  'Somalia',
  'Sri Lanka',
  'St. Kitts und Nevis',
  'St. Lucia',
  'St. Vincent und die Grenadinen',
  'Südafrika',
  'Sudan',
  'Südsudan',
  'Suriname',
  'Syrien',
  'Tadschikistan',
  'Taiwan',
  'Tansania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad und Tobago',
  'Tschad',
  'Tunesien',
  'Türkei',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'Uruguay',
  'Usbekistan',
  'Vanuatu',
  'Vatikanstadt',
  'Venezuela',
  'Vereinigte Arabische Emirate',
  'Vereinigte Staaten',
  'Vereinigtes Königreich',
  'Vietnam',
  'Zentralafrikanische Republik',
  'staatenlos',
  'ungeklärt',
] as const;

const norm = (s: string) => s.trim().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');

/** Gespeicherten (auch alten Freitext-)Wert einem Staat der Liste zuordnen: „rumänisch“ → Rumänien, „Türkei“ → Türkei. */
export function countryOf(value: string | null | undefined): string | null {
  const v = norm(value ?? '');
  if (!v) return null;
  const all = [...FREE_MOVEMENT_COUNTRIES, ...OTHER_COUNTRIES];
  const exact = all.find((c) => norm(c) === v);
  if (exact) return exact;
  const ADJ: Record<string, string> = {
    deutsch: 'Deutschland',
    turk: 'Türkei',
    turkisch: 'Türkei',
    polnisch: 'Polen',
    rumanisch: 'Rumänien',
    bulgarisch: 'Bulgarien',
    kroatisch: 'Kroatien',
    ungarisch: 'Ungarn',
    italienisch: 'Italien',
    griechisch: 'Griechenland',
    spanisch: 'Spanien',
    portugiesisch: 'Portugal',
    franzosisch: 'Frankreich',
    osterreichisch: 'Österreich',
    slowakisch: 'Slowakei',
    slowenisch: 'Slowenien',
    tschechisch: 'Tschechien',
    serbisch: 'Serbien',
    bosnisch: 'Bosnien und Herzegowina',
    kosovarisch: 'Kosovo',
    albanisch: 'Albanien',
    mazedonisch: 'Nordmazedonien',
    nordmazedonisch: 'Nordmazedonien',
    montenegrinisch: 'Montenegro',
    ukrainisch: 'Ukraine',
    russisch: 'Russland',
    afghanisch: 'Afghanistan',
    syrisch: 'Syrien',
    irakisch: 'Irak',
    iranisch: 'Iran',
    eritreisch: 'Eritrea',
    athiopisch: 'Äthiopien',
    somalisch: 'Somalia',
    nigerianisch: 'Nigeria',
    pakistanisch: 'Pakistan',
    indisch: 'Indien',
    vietnamesisch: 'Vietnam',
    philippinisch: 'Philippinen',
    marokkanisch: 'Marokko',
    tunesisch: 'Tunesien',
    georgisch: 'Georgien',
    moldauisch: 'Moldau',
    litauisch: 'Litauen',
    lettisch: 'Lettland',
    estnisch: 'Estland',
    niederlandisch: 'Niederlande',
    belgisch: 'Belgien',
    schwedisch: 'Schweden',
    danisch: 'Dänemark',
    finnisch: 'Finnland',
    irisch: 'Irland',
    zypriotisch: 'Zypern',
    maltesisch: 'Malta',
    luxemburgisch: 'Luxemburg',
    schweizerisch: 'Schweiz',
    norwegisch: 'Norwegen',
    britisch: 'Vereinigtes Königreich',
    amerikanisch: 'Vereinigte Staaten',
    usa: 'Vereinigte Staaten',
    chinesisch: 'China',
    brasilianisch: 'Brasilien',
    kolumbianisch: 'Kolumbien',
    ghanaisch: 'Ghana',
    kamerunisch: 'Kamerun',
    gambisch: 'Gambia',
    senegalesisch: 'Senegal',
    guineisch: 'Guinea',
    algerisch: 'Algerien',
    agyptisch: 'Ägypten',
    libanesisch: 'Libanon',
    jordanisch: 'Jordanien',
    armenisch: 'Armenien',
    aserbaidschanisch: 'Aserbaidschan',
    kasachisch: 'Kasachstan',
    usbekisch: 'Usbekistan',
    bangladeschisch: 'Bangladesch',
    srilankisch: 'Sri Lanka',
    thailandisch: 'Thailand',
  };
  const a = v.replace(/e$/, '').replace(/[^a-z]/g, '');
  if (ADJ[a]) return ADJ[a];
  return all.find((c) => norm(c).startsWith(v) && v.length >= 4) ?? null;
}

/** EU/EWR/Schweiz (Freizügigkeit)? */
export const isFreeMovementCountry = (c: string) =>
  (FREE_MOVEMENT_COUNTRIES as readonly string[]).includes(c);
