/*
 * Auswahllisten für die Personalstammdaten: Krankenkassen (gesetzliche Kassen in Deutschland, Stand 2026 – Namen ändern
 * sich durch Fusionen; fehlt eine, „Sonstige“ wählen und im Info-Feld ergänzen) und Sprachen.
 */
export const HEALTH_INSURERS = [
  'AOK Baden-Württemberg',
  'AOK Bayern',
  'AOK Bremen/Bremerhaven',
  'AOK Hessen',
  'AOK Niedersachsen',
  'AOK Nordost',
  'AOK NordWest',
  'AOK PLUS',
  'AOK Rheinland/Hamburg',
  'AOK Rheinland-Pfalz/Saarland',
  'AOK Sachsen-Anhalt',
  'BARMER',
  'DAK-Gesundheit',
  'Techniker Krankenkasse (TK)',
  'KKH Kaufmännische Krankenkasse',
  'hkk Krankenkasse',
  'HEK – Hanseatische Krankenkasse',
  'IKK classic',
  'IKK gesund plus',
  'IKK – Die Innovationskasse',
  'IKK Südwest',
  'BIG direkt gesund',
  'KNAPPSCHAFT',
  'SVLFG (Landwirtschaftliche Krankenkasse)',
  'Audi BKK',
  'BAHN-BKK',
  'BKK Akzo Nobel Bayern',
  'BKK Diakonie',
  'BKK DürkoppAdler',
  'BKK EUREGIO',
  'BKK exklusiv',
  'BKK Faber-Castell & Partner',
  'BKK firmus',
  'BKK Freudenberg',
  'BKK GILDEMEISTER SEIDENSTICKER',
  'BKK HENSCHEL Plus',
  'BKK Herkules',
  'BKK Linde',
  'BKK MAHLE',
  'bkk melitta hmr',
  'BKK Mobil',
  'BKK MTU',
  'BKK PFAFF',
  'BKK Pfalz',
  'BKK ProVita',
  'BKK Public',
  'BKK Rieker.RICOSTA.Weisser',
  'BKK Salzgitter',
  'BKK Scheufelen',
  'BKK SBH',
  'BKK Technoform',
  'BKK Textilgruppe Hof',
  'BKK VDN',
  'BKK VerbundPlus',
  'BKK Werra-Meissner',
  'BKK WIRTSCHAFT & FINANZEN',
  'BKK ZF & Partner',
  'BKK24',
  'Bertelsmann BKK',
  'BMW BKK',
  'Bosch BKK',
  'Continentale Betriebskrankenkasse',
  'Debeka BKK',
  'energie-BKK',
  'Heimat Krankenkasse',
  'Karl Mayer BKK',
  'Koenig & Bauer BKK',
  'Krones BKK',
  'Mercedes-Benz BKK',
  'Merck BKK',
  'mhplus Krankenkasse',
  'Novitas BKK',
  'pronova BKK',
  'R+V Betriebskrankenkasse',
  'Salus BKK',
  'SECURVITA Krankenkasse',
  'Siemens-Betriebskrankenkasse (SBK)',
  'SKD BKK',
  'Südzucker BKK',
  'TUI BKK',
  'VIACTIV Krankenkasse',
  'vivida bkk',
  'WMF BKK',
  'Privat versichert (PKV)',
  'Sonstige',
];

/** Sprachen der Mitarbeitenden; die ersten sieben gibt es auch als Sprache der Handy-App. */
export const LANGUAGES: { name: string; app?: string }[] = [
  { name: 'Deutsch', app: 'de' },
  { name: 'Englisch', app: 'en' },
  { name: 'Rumänisch', app: 'ro' },
  { name: 'Türkisch', app: 'tr' },
  { name: 'Polnisch', app: 'pl' },
  { name: 'Kroatisch/Bosnisch/Serbisch', app: 'hr' },
  { name: 'Bulgarisch', app: 'bg' },
  { name: 'Arabisch' },
  { name: 'Ukrainisch' },
  { name: 'Russisch' },
  { name: 'Albanisch' },
  { name: 'Griechisch' },
  { name: 'Italienisch' },
  { name: 'Spanisch' },
  { name: 'Portugiesisch' },
  { name: 'Ungarisch' },
  { name: 'Slowakisch' },
  { name: 'Tschechisch' },
  { name: 'Persisch (Farsi/Dari)' },
  { name: 'Kurdisch' },
  { name: 'Tigrinya' },
  { name: 'Somali' },
  { name: 'Vietnamesisch' },
];

/** App-Sprache aus den gewählten Sprachen: erste, die die Handy-App kann (sonst Deutsch). */
export function appLanguageOf(languages: string[]): string {
  for (const l of languages) {
    const hit = LANGUAGES.find(
      (x) => x.name.toLowerCase() === l.trim().toLowerCase() || x.app === l.trim().toLowerCase(),
    );
    if (hit?.app) return hit.app;
  }
  return 'de';
}
